[package]
name = "grpcio-sys"
version = "0.4.0"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["grpc", "bindings"]
repository = "https://github.com/pingcap/grpc-rs"
homepage = "https://github.com/pingcap/grpc-rs"
documentation = "https://docs.rs/grpcio-sys"
description = "FFI bindings to gRPC c core library"
categories = ["external-ffi-bindings", "network-programming"]
build = "build.rs"
exclude = [
    "grpc/doc/*",
    "grpc/etc/*",
    "grpc/examples/*",
    "grpc/Makefile",
    "grpc/templates/*",
    "grpc/src/android/*",
    "grpc/src/csharp/*",
    "grpc/src/boringssl/crypto_test_data.cc",
    "grpc/src/node/*",
    "grpc/src/objective-c/*",
    "grpc/src/php/*",
    "grpc/src/python/*",
    "grpc/src/ruby/*",
    "grpc/vsprojects/*",
    "grpc/test/core/end2end/*",
    "grpc/third_party/abseil-cpp/*",
    "grpc/third_party/benchmark/*",
    "grpc/third_party/bloaty/*",
    "grpc/third_party/boringssl/fuzz/*",
    "grpc/third_party/boringssl/crypto/cipher_extra/test/*",
    "grpc/third_party/boringssl/third_party/android-cmake/*",
    "grpc/third_party/boringssl/util/*",
    "grpc/third_party/boringssl-with-bazel/*",
    "grpc/third_party/gflags/*",
    "grpc/third_party/googletest/*",
    "grpc/third_party/libcxx/*",
    "grpc/third_party/libcxxabi/*",
    "grpc/third_party/objective_c/*",
    "grpc/third_party/protobuf/*",
    "grpc/third_party/rake-compiler-dock/*",
    "grpc/third_party/toolchan/*",
    "grpc/tools/run_tests/generated/*",
]

[dependencies]
libc = "0.2"

[features]
default = []
secure = []
openssl = ["secure"]

[build-dependencies]
cc = "1.0"
cmake = "0.1.27"
pkg-config = "0.3"
